### ISSUE TITLE
Invalid key for Launchpad PPA

### ISSUE THREAD

**Issue by kynan** [thoughtbot/rcm#157] opened 2015-10-07 19:11 UTC
The key for the launchpad PPA given in the README appears to be invalid:

```
W: GPG error: http://ppa.launchpad.net trusty Release: The following signatures were invalid: BADSIG 4609D1E5ECA538E6 Launchpad PPA for Martin Frost
```

**Comment by mike-burns** [comment] 2015-11-01 18:49
Ping @Frost .

**Comment by Frost** [comment] 2015-11-02 08:58
Thanks. I'll have a look at it tonight.

**Comment by Frost** [comment] 2015-11-04 17:40
I just now noticed that my key listed in [DEVELOPERS.md](DEVELOPERS.md) is not the same one that I used for the PPA.

This might be a bit confusing, but it is not why the BADSIG is happening. Both keys are mine, so that should not be a problem. I will investigate this further.

**Comment by Frost** [comment] 2015-11-04 17:54
@kynan What version of Ubuntu are you using, and exactly what command are you running when you get this error?

I think I need some more info to be able to reproduce this.

I just ran the install instructions (copy-pasta from [README.md](/thoughtbot/rcm/blob/master/README.md) on a fresh install of Ubuntu 14.04 (Trusty Tahr).

```
sudo add-apt-repository ppa:martin-frost/thoughtbot-rcm
sudo apt-get update
sudo apt-get install rcm
```

The reason I'm using Ubuntu 14.04 is because that's one release that there actually exists packages for.

Here's the output:

```
frost@tiamat ~ $ ssh root@46.101.218.113
The authenticity of host '46.101.218.113 (46.101.218.113)' can't be established.
ECDSA key fingerprint is 93:ab:85:bb:ed:0b:31:b5:a9:b3:62:33:43:6e:65:5e.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '46.101.218.113' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-57-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Wed Nov  4 12:42:15 EST 2015

  System load: 0.0               Memory usage: 10%   Processes:       50
  Usage of /:  7.3% of 19.56GB   Swap usage:   0%    Users logged in: 0

  Graph this data and manage this system at:
    https://landscape.canonical.com/

root@rcm-test:~# sudo add-apt-repository ppa:martin-frost/thoughtbot-rcm
 An rc file manager, written by thoughtbot.

Source code lives at https://github.com/thoughtbot/rcm
 More info: https://launchpad.net/~martin-frost/+archive/ubuntu/thoughtbot-rcm
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmp3b4l_8mz/secring.gpg' created
gpg: keyring `/tmp/tmp3b4l_8mz/pubring.gpg' created
gpg: requesting key ECA538E6 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp3b4l_8mz/trustdb.gpg: trustdb created
gpg: key ECA538E6: public key "Launchpad PPA for Martin Frost" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
root@rcm-test:~# sudo apt-get update && sudo apt-get install rcm
Ign http://ppa.launchpad.net trusty InRelease
Get:1 http://security.ubuntu.com trusty-security InRelease [64.4 kB]           
Get:2 http://ppa.launchpad.net trusty Release.gpg [836 B]                      
Get:3 http://ppa.launchpad.net trusty Release [15.1 kB]                        
Get:4 http://security.ubuntu.com trusty-security/main Sources [98.0 kB]        
Get:5 http://ppa.launchpad.net trusty/main amd64 Packages [380 B]              
Get:6 http://security.ubuntu.com trusty-security/universe Sources [31.0 kB]    
Get:7 http://ppa.launchpad.net trusty/main i386 Packages [380 B]               
Get:8 http://security.ubuntu.com trusty-security/main amd64 Packages [362 kB]  
Get:9 http://ppa.launchpad.net trusty/main Translation-en [322 B]              
Get:10 http://security.ubuntu.com trusty-security/universe amd64 Packages [117 kB]
Get:11 http://security.ubuntu.com trusty-security/main i386 Packages [342 kB]  
Get:12 http://security.ubuntu.com trusty-security/universe i386 Packages [117 kB]
Ign http://mirrors.digitalocean.com trusty InRelease                           
Get:13 http://security.ubuntu.com trusty-security/main Translation-en [196 kB] 
Get:14 http://mirrors.digitalocean.com trusty-updates InRelease [64.4 kB]      
Get:15 http://security.ubuntu.com trusty-security/universe Translation-en [68.4 kB]
Hit http://mirrors.digitalocean.com trusty Release.gpg                         
Get:16 http://mirrors.digitalocean.com trusty-updates/main Sources [242 kB]
Get:17 http://mirrors.digitalocean.com trusty-updates/universe Sources [143 kB]
Get:18 http://mirrors.digitalocean.com trusty-updates/main amd64 Packages [639 kB]
Get:19 http://mirrors.digitalocean.com trusty-updates/universe amd64 Packages [326 kB]
Get:20 http://mirrors.digitalocean.com trusty-updates/main i386 Packages [620 kB]
Get:21 http://mirrors.digitalocean.com trusty-updates/universe i386 Packages [327 kB]
Get:22 http://mirrors.digitalocean.com trusty-updates/main Translation-en [310 kB]
Get:23 http://mirrors.digitalocean.com trusty-updates/universe Translation-en [172 kB]
Hit http://mirrors.digitalocean.com trusty Release                             
Hit http://mirrors.digitalocean.com trusty/main Sources
Hit http://mirrors.digitalocean.com trusty/universe Sources          
Hit http://mirrors.digitalocean.com trusty/main amd64 Packages             
Hit http://mirrors.digitalocean.com trusty/universe amd64 Packages        
Hit http://mirrors.digitalocean.com trusty/main i386 Packages             
Hit http://mirrors.digitalocean.com trusty/universe i386 Packages         
Hit http://mirrors.digitalocean.com trusty/main Translation-en
Hit http://mirrors.digitalocean.com trusty/universe Translation-en
Ign http://mirrors.digitalocean.com trusty/main Translation-en_US              
Ign http://mirrors.digitalocean.com trusty/universe Translation-en_US          
Fetched 4,256 kB in 7s (554 kB/s)                                              
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  rcm
0 upgraded, 1 newly installed, 0 to remove and 63 not upgraded.
Need to get 18.1 kB of archives.
After this operation, 80.9 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/martin-frost/thoughtbot-rcm/ubuntu/ trusty/main rcm all 1.2.3-1ppa1 [18.1 kB]
Fetched 18.1 kB in 0s (216 kB/s)
Selecting previously unselected package rcm.
(Reading database ... 86793 files and directories currently installed.)
Preparing to unpack .../rcm_1.2.3-1ppa1_all.deb ...
Unpacking rcm (1.2.3-1ppa1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up rcm (1.2.3-1ppa1) ...
root@rcm-test:~# 
```

**Comment by kynan** [comment] 2015-11-16 21:12
@Frost I did pretty much exactly the same as you did and I'm on Mint 17 (Ubuntu 14.04 derivative). I can't tell what changed but I no longer get the warning.

**Comment by mike-burns** [comment] 2016-12-26 21:46
Seems like things work now? Closing, but let me know if I mis-interpret this.

**Closed by mike-burns** 2016-12-26 21:46 UTC
Labels: packaging
