### ISSUE TITLE
Add .rcmignore

### ISSUE THREAD

**Issue by gfontenot** [thoughtbot/rcm#86] opened 2014-05-05 23:25 UTC
The `EXCLUDES` variable in `rcrc` is great, but feels limited. In my case, I would love to be able to set exclude patterns on a tag by tag basis. It feels like a good solution to this would be to have the ability to define an `.rcmignore` file that works much like `.gitignore`.

**Comment by graysonwright** [comment] 2015-01-07 04:40
@mike-burns hrm.... Any thoughts?

```bash
$ rcdn
$ cat ~/.dotfiles/rcrc
EXCLUDES=README.md
$ rcup
$ ls -l ~/.README.md
lrwxr-xr-x  1 grayson  staff  34 Jan  6 20:33 /Users/grayson/.README.md -> /Users/grayson/.dotfiles/README.md
```

**Comment by mike-burns** [comment] 2015-01-07 12:35
@graysonwright can you post:

    lsrc -vvv 2>&1 | grep README

**Comment by pbrisbin** [comment] 2015-01-07 15:14
`rcdn` is going to remove `~/.rcrc` which means it's not going to have an effect when you `rcup`.

`RCRC=$HOME/.dotfiles/rcrc rcup` is the way to bootstrap while respecting a not-yet-installed `rcrc`.

**Comment by graysonwright** [comment] 2015-01-07 17:59
@pbrisbin – that's the use case that an `.rcignore` would solve for me...

It just seems a bit strange that I'd need an existing dotfile in place to properly install the rest of my dotfiles. Seems like a chicken-or-egg situation. Normally I'd be okay with prefixing `RCRC=$HOME/.dotfiles/rcrc` onto the command, but since I wouldn't be able to alias that without my dotfiles installed already, I feel like I'd forget and have to check the man page every time before I bootstrap.

**Comment by pbrisbin** [comment] 2015-01-07 18:16
I only mentioned it because mike was offering further debugging instructions, but the situation you have is expected behavior.

I fully support the `.rcignore` feature, but solving this bootstrap issue is not its goal, that's just a pleasant side-effect.

You can have things other than `EXCLUDE`/`INCLUDE` in your `rcrc` which you may need to happen when bootstrapping a new system. I've personally learned to use `RCRC` in these cases. The only other fix would be for `rcup` to look (in a hardcoded way) for `~/.dotfiles/rcrc`. That's not 100% robust and has been discussed in other PRs. I'm against it myself.

**Comment by graysonwright** [comment] 2015-01-08 07:10
@pbrisbin I'm relatively new to RCM. If you can recall any offhand, would you mind linking to a discussion about looking up `~/.dotfiles/rcrc`?

Thanks!

**Comment by mike-burns** [comment] 2015-01-08 10:58
Unrelated to this Issue, but related to @graysonwright 's desires: I would be interested in a separate tool to make life easier for people who store their rc files in a VCS, and especially a tool for people with multiple dotfiles dirs.

**Comment by pbrisbin** [comment] 2015-01-08 14:22
> would you mind linking to a discussion

#103

**Comment by mike-burns** [comment] 2015-06-05 11:32
We already have EXCLUDES and INCLUDES in rcrc(5), so I'm closing this. Please open a pull request if you want this feature separately from rcrc(5).

**Closed by mike-burns** 2015-06-05 11:32 UTC
Labels: discussion-needed, enhancement
